---
- name: Update Ubuntu packages 
  apt:
    update_cache: yes

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted